ACCEPTED_MIME_TYPES = [
    'application/json', 'application/pdf', 'image/png', 'video/mp4']
APP_NAME = ''

DEFAULT_TOKEN_COUNT = 20

EMAIL_CONFIRMATION_LINK_LIFESPAN = (60 * 60)

MAX_USER_BIO_LENGTH = 140
MIN_LOCATION_NAME_LENGTH = 2
MIN_PASSWORD_LENGTH = 6
MIN_STORY_TEXT_LENGTH = 1
MIN_POST_TEXT_LENGTH = 1
MIN_USER_BIO_LENGTH = 4
MIN_USERNAME_LENGTH = 2

NESTED_VALUES_LIMIT = 20

SUPPORTED_HTTP_METHODS = ['GET', 'POST', 'PATCH', 'PUT', 'DELETE']
