APP_NAME = ''

DEFAULT_TOKEN_COUNT = 20

EMAIL_CONFIRMATION_LINK_LIFESPAN = (60 * 60)

MIN_USERNAME_LENGTH = 2
MIN_USER_BIO_LENGTH = 4

SUPPORTED_HTTP_METHODS = ['GET', 'POST', 'PATCH', 'PUT', 'DELETE']
